name: ProLoginBar
main: me.sedattr.loginbar.LoginBar
version: 1.0
author: SedatTR
description: Advanced login bar plugin for auth lobby with title, subtitle, action bar and boss bar!
softdepend:
  - AuthMe
commands:
  send:
    description: You can send player to bungeecord server.
    usage: /send [player] (name)
  server:
    description: Sends to bungeecord server.
    usage: /server (name)